apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleBinding.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.clusterRoleBinding.serviceAcct }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterRoleBinding.clusterRole }}
  apiGroup: rbac.authorization.k8s.io